### ISSUE TITLE
nix alias (and maybe url) from config

### ISSUE THREAD

**Issue by ack** [CenturyLinkCloud/clc-sdk#11]
we can infer alias from the login results (and set it in the client config object). proposed patch would be to remove the alias arg from NewConfig, capture it in Authenticate() and patch all remaining refs? Is there a use case where the user would *not* belong to the account alias provided?

similarly, was wondering whether we could move baseUrl from a required arg. support would be via env var or custom file-based config. 

do you have a running list of sdk clients at this point?

**Comment by mikebeyer** [comment]
Yea, I had an issue open for dropping alias.  We still want the ability for someone to use the Alias modification of the config so they can make changes to sub-accounts.

I'd like to hear your thoughts on baseURL.  It's really useful for hitting the dev/qa endpoints, which is why it's an optional configuration value.  I don't see many customers needing to change it.

**Comment by ack** [comment]
I see. Didn't think about sub-accounts. How about (for both):

- leave signature unchanged
- when non-empty, set in config
- when absent, use the returned alias or url from the token

empty-string arguments seems awkward though

= OR = 

a new method DefaultConfig which sets alias-from-token and baseURL 

= OR = 

NewConfig just fills in Username and Password, caller is responsible for direct config access for everything else?



On an aside, I think UserAgent would be an important parameter as well, since ultimately we'd like to ident every application using the sdk through.

**Comment by mikebeyer** [comment]
Regarding aliases in general, I think we're good to just grab it from the login. And if they want to use a different alias, [this](https://github.com/CenturyLinkCloud/clc-sdk/blob/master/client.go#L42-L44) is available for users if they feel the need to subaccount. 

So for simplicity, I think you're good removing it as a required config param, and drawing it from the Login call.  Maybe leave it in to be set from the environment?  I could go either way there.

UserAgent is interesting, I think it should be configurable, we should have a default.  I believe that's what amazon does.
