### ISSUE TITLE
HTTP header details

### ISSUE THREAD

**Issue by ctl-jkb** [CenturyLinkCloud/clc-sdk#5]
Details about the HTTP requests made against the CLC API:
-- add the Host header (these are HTTP/1.1 requests, right?)
-- add the Accept:application/json header (sdk docs say this is required, though it works fine without)
-- omit the Content-Type header on requests that have no message body

**Comment by mikebeyer** [comment]
Host header is managed automatically by go's http library.  It uplifts the Header from the map into the requests host value.
